[package]
name = "tilebound_solid"
authors = ["Christopher Edward Dawn"]
version = "0.3.0"
edition = "2024"
description = "A small boolean/bit tilemap collision libary"
readme = "README.md"
repository = "https://github.com/cedtwo/tilebound.git"
license = "MIT OR Apache-2.0"
keywords = ["tilemap", "physics", "collision", "platformer", "topdown"]
categories = ["game-development"]

[dependencies]
bitvec = "1.1.1"
tilebound = { version = "0.3.1" }

[dev-dependencies]
macroquad = { version = "0.4" }

[features]
default = []
arraymap = ["tilebound/arraymap"]
bitmap = ["tilebound/bitmap"]

[[test]]
name = "sweep"
required-features = ["arraymap"]

[[example]]
name = "minimal"
path = "examples/minimal.rs"
required-features = ["bitmap"]

[[example]]
name = "platformer"
path = "examples/platformer.rs"
required-features = ["bitmap"]
