[package]
name = "tilebound"
authors = ["Christopher Edward Dawn"]
version = "0.2.1"
edition = "2024"
description = "A framework for resolving tilemap collisions."
readme = "README.md"
repository = "https://github.com/cedtwo/tilebound.git"
license = "MIT OR Apache-2.0"
keywords = ["tilemap", "physics", "collision", "platformer", "topdown"]
categories = ["game-development"]

[dependencies]
marker_value = { version = "0.1.0" }
num-traits = "0.2.19"
bitvec = { version = "1.1.1", optional = true }
subbyte_index = { version = "0.1.1", optional = true }
ndarray = { version = "0.17.2", optional = true }
mdarray = { version = "0.8.0", optional = true }

[features]
default = []
bitmap = ["dep:bitvec"]
packmap = ["dep:subbyte_index"]
arraymap = []
ndarray = ["dep:ndarray"]
mdarray = ["dep:mdarray"]
