[package]
name = "tilebound_view"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
marker_value = { workspace = true }
tilebound_plane = { path = "../plane" }
ndarray = { version = "0.17", optional = true }
mdarray = { version = "0.7", optional = true }
bitvec = { workspace = true, optional = true }
subbyte_index = { workspace = true, optional = true }

[features]
default = []
arraymap = []
bitmap = ["dep:bitvec"]
packmap = ["dep:subbyte_index"]
ndarray = ["dep:ndarray"]
mdarray = ["dep:mdarray"]
